version: '3.4'
services:
  Jenkinsspring:
    image: jenkinsspring:latest
    network_mode: bridge
    container_name: jenkinsspring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8080
